### ISSUE TITLE
Can ir delete BOTs from other users and links with referreral invitacionto join other group made from visitors 

### ISSUE THREAD

**Issue by AlexisValera** [artiya4u/silencert#1]
Can ir delete BOTs from other users and links with referreral invitacionto join other group made from visitors 

Can it be applied other issues eraser and derivates

**Comment by artiya4u** [comment]
Please give me examples of the referral link.

**Comment by artiya4u** [comment]
Bot now will remove the message contain an invite link to another group like "https://t.me/joinchat/ANOTHER_GROUP"
