### ISSUE TITLE
Join/Left Notifications

### ISSUE THREAD

**Issue by delusive** [artiya4u/silencert#2]
Not an issue with your bot per se, but have you figured out any way to disable the notifications sent out when joining/leaving a group, without actually fully disabling notifications, so that notifications only go out for normal messages?  Obviously the status message shows up and is instantly deleted by the bot, but the notifications still go out, and that clouds the actual message notfications.

Thanks!

**Comment by artiya4u** [comment]
The bot cannot control client notification behavior. Please consider open the issue on the Telegram client repositories. I personally mute the chat of the crowded group.
