### ISSUE TITLE
admins should be able to post invite links

### ISSUE THREAD

**Issue by gnadelwartz** [artiya4u/silencert#3]
hi, i like your bot very much because of his simplicity.

I takes me some headscratches to realize that it now also remove invites.
in general this is a good Idea, but I would prefer to disallow for regular users only.
a group admin should be able to post invites.

for now I must use the workaround to remove the bot as Admin an re add him afterwards.

**Comment by artiya4u** [comment]
Fixed, Thank for feedback :smile:

**Comment by gnadelwartz** [comment]
great! is the change already live?
